# Configuration file for the pi that operates as an alarm system.
#
# + Make copy of your current file before making changes.
# + place this fine on a USB flash drive
# 
owner-name : first last
owner-email : sample@email.com
owner-cell : 123.456.7890
notify-email : no
notify-text : yes
notify-phone : no

zone : 61 = Laundry Room Door
zone : 57 = Front Door
zone : 14 = Back Door 1
zone : 52 = Back Door 2

wifi-ssid : wifi network id here
wifi-psk : wifi password
wifi-key-management: wifi key management